import React, { useEffect, useMemo, useRef, useState } from "react";
import {
  Users, FileText, Video, Mic, MicOff, VideoOff,
  PhoneOff, Send, Code2, Star, Upload, CheckCircle2, AlertTriangle, XCircle,
  ArrowRight, X, Flame, Target, Sparkles, Search, Calendar, Radio,
} from "lucide-react";
import "./InterviewReady.css";

const FEATURES = [
  { key: "mock", icon: Users, tone: "blue", title: "Peer-to-Peer Mock Interviews", description: "Practice live with another student through video, chat, and a shared code editor." },
  { key: "resume", icon: FileText, tone: "purple", title: "AI Resume Scanner", description: "Upload your resume and get an ATS score, missing keywords, and practical fixes." },
  { key: "heatmap", icon: Flame, tone: "rose", title: "Weakness Heatmap", description: "See which topics are costing you points and jump into targeted practice." },
];

const ROLE_KEYWORDS = {
  "Full Stack Developer": ["react", "node", "express", "mongodb", "rest api", "git", "javascript", "sql", "docker", "system design"],
  "Data Scientist": ["python", "pandas", "numpy", "machine learning", "sql", "statistics", "scikit-learn", "tensorflow", "data visualization", "a/b testing"],
  "Backend Engineer": ["java", "spring boot", "sql", "microservices", "rest api", "docker", "kubernetes", "aws", "redis", "system design"],
};
const SUBJECTS = ["DSA", "DBMS", "OS", "Networks", "OOP"];
const TOPICS = { DSA: ["Arrays", "Trees", "Graphs", "DP", "Recursion"], DBMS: ["Normalization", "Joins", "Indexing", "Transactions", "ER Models"], OS: ["Paging", "Scheduling", "Deadlocks", "Threads", "File Systems"], Networks: ["TCP/IP", "DNS", "Routing", "HTTP", "Sockets"], OOP: ["Inheritance", "Polymorphism", "Design Patterns", "Encapsulation", "Interfaces"] };

function scoreFor(subject, topic) { return [...subject + topic].reduce((score, character) => (score * 31 + character.charCodeAt(0)) % 97, 0) % 100; }
function scoreTone(score) { return score < 40 ? "weak" : score < 70 ? "okay" : "strong"; }

function HomePage({ setPage }) {
  return <main className="ready-home"><div className="ready-container"><div className="ready-intro"><span className="ready-eyebrow"><Sparkles /> Interview readiness lab</span><h1>Three new ways to <em>get interview-ready</em></h1><p>Build confidence with live practice, sharper resumes, and a clear view of what to improve next.</p></div><div className="ready-feature-grid">{FEATURES.map(({ key, icon: Icon, tone, title, description }) => <button className={`ready-feature feature-${tone}`} key={key} onClick={() => setPage(key)}><Icon /><h2>{title}</h2><p>{description}</p><span>Open feature <ArrowRight /></span></button>)}</div></div></main>;
}

function MockInterview() {
  const [stage, setStage] = useState("lobby");
  const [topic, setTopic] = useState("DSA");
  const [mode, setMode] = useState("instant");
  if (stage === "matching") return <Matching topic={topic} onMatched={() => setStage("room")} />;
  if (stage === "room") return <MockRoom topic={topic} onEnd={() => setStage("rated")} />;
  if (stage === "rated") return <Rating onDone={() => setStage("lobby")} />;
  return <main className="ready-page ready-soft-blue"><div className="ready-narrow"><div className="ready-intro"><span className="live-badge"><Radio /> Live and free</span><h1>Find a <em>peer</em> to interview with</h1><p>Practice out loud and get real feedback from another student.</p></div><section className="ready-card setup-card"><label>Choose a topic</label><div className="choice-grid">{["DSA", "Web Dev", "HR"].map((item) => <button className={topic === item ? "selected" : ""} key={item} onClick={() => setTopic(item)}>{item}</button>)}</div><label>When</label><div className="timing-grid"><button className={mode === "instant" ? "selected" : ""} onClick={() => setMode("instant")}><Radio /><span><strong>Right now</strong><small>Match with someone online now</small></span></button><button className={mode === "schedule" ? "selected" : ""} onClick={() => setMode("schedule")}><Calendar /><span><strong>Schedule for later</strong><small>Pick a slot that works for you</small></span></button></div><button className="ready-primary" onClick={() => mode === "instant" ? setStage("matching") : window.alert("We will email you a link before your slot.")}>{mode === "instant" ? "Find a Peer Now" : "Schedule for Later"} <ArrowRight /></button></section></div></main>;
}

function Matching({ topic, onMatched }) { useEffect(() => { const timer = setTimeout(onMatched, 1800); return () => clearTimeout(timer); }, [onMatched]); return <main className="matching"><div className="spinner" /><h1>Finding a {topic} partner...</h1><p>Hang tight, this usually takes a few seconds.</p></main>; }

function MockRoom({ topic, onEnd }) {
  const [mic, setMic] = useState(true); const [camera, setCamera] = useState(true); const [code, setCode] = useState("// Shared editor - both peers can type here\nfunction twoSum(nums, target) {\n  \n}"); const [draft, setDraft] = useState(""); const [messages, setMessages] = useState(["Hey! Ready when you are."]);
  const send = () => { if (draft.trim()) { setMessages((items) => [...items, draft.trim()]); setDraft(""); } };
  return <main className="mock-room"><header><span><i /> Live session - {topic} Round</span><button onClick={onEnd}><PhoneOff /> End session</button></header><div className="room-grid"><section className="video-column"><div className="video-stack"><div className="video-tile"><div className="person person-blue">P</div><small>You</small>{!camera && <VideoOff />}</div><div className="video-tile"><div className="person person-purple">R</div><small>Rahul (peer)</small></div></div><div className="room-controls"><button className={!mic ? "off" : ""} onClick={() => setMic((value) => !value)}>{mic ? <Mic /> : <MicOff />}</button><button className={!camera ? "off" : ""} onClick={() => setCamera((value) => !value)}>{camera ? <Video /> : <VideoOff />}</button></div><div className="chat-list">{messages.map((message, index) => <p className={index % 2 ? "mine" : ""} key={`${message}-${index}`}>{message}</p>)}</div><div className="chat-input"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => event.key === "Enter" && send()} placeholder="Message your peer..." /><button onClick={send}><Send /></button></div></section><section className="editor"><div><Code2 /> Collaborative editor</div><textarea value={code} onChange={(event) => setCode(event.target.value)} spellCheck={false} /></section></div></main>;
}

function Rating({ onDone }) { const [rating, setRating] = useState(0); return <main className="ready-page ready-soft-blue centered"><section className="ready-card rating-card"><h1>How was your session?</h1><p>Rate your peer to help keep matching quality high.</p><div className="stars">{[1, 2, 3, 4, 5].map((number) => <button key={number} onClick={() => setRating(number)}><Star className={number <= rating ? "filled" : ""} /></button>)}</div><button className="ready-primary" onClick={onDone}>Submit and return to lobby</button></section></main>; }

function ResumeScanner() {
  const [fileName, setFileName] = useState(""); const [text, setText] = useState(""); const [role, setRole] = useState("Full Stack Developer"); const [report, setReport] = useState(null); const [dragOver, setDragOver] = useState(false); const inputRef = useRef(null);
  const readFile = (file) => { if (!file) return; setFileName(file.name); if (file.type === "text/plain" || file.name.endsWith(".txt")) { const reader = new FileReader(); reader.onload = (event) => setText(event.target.result || ""); reader.readAsText(file); } else setText("Experienced developer skilled in javascript, react, and git. Built REST APIs and worked with sql databases. Familiar with docker."); };
  const analyze = () => { const keywords = ROLE_KEYWORDS[role]; const lower = text.toLowerCase(); const present = keywords.filter((keyword) => lower.includes(keyword)); const missing = keywords.filter((keyword) => !lower.includes(keyword)); const words = text.trim().split(/\s+/).filter(Boolean).length; const suggestions = []; if (missing.length) suggestions.push(`Add measurable bullet points that mention: ${missing.slice(0, 4).join(", ")}.`); if (words < 150) suggestions.push("Aim for 400-600 words with concrete project details."); if (!/\d/.test(text)) suggestions.push("Quantify impact with percentages, users served, or time saved."); suggestions.push("Lead bullet points with strong action verbs such as Built, Led, and Optimized."); setReport({ score: Math.min(100, Math.round((present.length / keywords.length) * 60) + Math.min(20, Math.round((words / 300) * 20)) + 15), present, missing, suggestions }); };
  if (report) return <ResumeReport report={report} role={role} fileName={fileName} onBack={() => setReport(null)} />;
  return <main className="ready-page ready-soft-purple"><div className="ready-narrow"><div className="ready-intro"><h1>Scan your resume against <em>ATS filters</em></h1><p>Upload a resume, pick your target role, and get instant fixes.</p></div><section className="ready-card resume-card"><button className={`dropzone ${dragOver ? "drag-over" : ""}`} onClick={() => inputRef.current.click()} onDragOver={(event) => { event.preventDefault(); setDragOver(true); }} onDragLeave={() => setDragOver(false)} onDrop={(event) => { event.preventDefault(); setDragOver(false); readFile(event.dataTransfer.files[0]); }}><input ref={inputRef} type="file" accept=".pdf,.docx,.txt" onChange={(event) => readFile(event.target.files[0])} /> <Upload />{fileName ? <strong>{fileName} selected</strong> : <><strong>Drop your resume here</strong><small>PDF, DOCX, or TXT up to 5MB</small></>}</button><label>Target role<select value={role} onChange={(event) => setRole(event.target.value)}>{Object.keys(ROLE_KEYWORDS).map((item) => <option key={item}>{item}</option>)}</select></label><button className="ready-primary purple-primary" disabled={!text} onClick={analyze}>Analyze Resume <Search /></button>{!text && <small className="hint">Upload a file above to enable analysis.</small>}</section></div></main>;
}

function ResumeReport({ report, role, fileName, onBack }) { return <main className="ready-page ready-soft-purple"><div className="ready-container"><button className="back-button" onClick={onBack}>Back to scanner</button><section className="ready-card resume-summary"><div className="score-circle"><strong>{report.score}</strong><small>/ 100</small></div><div><span className="ready-eyebrow">ATS score - {role}</span><h1>{fileName || "your-resume.pdf"}</h1><p>{report.score >= 75 ? "Strong match - small tweaks can make it even better." : "A few keyword and formatting fixes will help a lot."}</p></div></section><div className="report-columns"><section className="ready-card"><h2><Search /> Keyword check</h2>{report.present.map((item) => <p className="report-line" key={item}><CheckCircle2 /> {item}</p>)}{report.missing.length > 0 && <><h3>Missing</h3>{report.missing.map((item) => <p className="report-line" key={item}><XCircle /> {item}</p>)}</>}</section><section className="ready-card"><h2><AlertTriangle /> Suggested fixes</h2>{report.suggestions.map((item) => <p className="suggestion" key={item}>{item}</p>)}</section></div></div></main>; }

function Heatmap() { const [selected, setSelected] = useState(null); const weakest = useMemo(() => SUBJECTS.flatMap((subject) => TOPICS[subject].map((topic) => ({ subject, topic, score: scoreFor(subject, topic) }))).sort((a, b) => a.score - b.score).slice(0, 3), []); return <main className="ready-page ready-soft-blue"><div className="ready-container"><div className="heatmap-heading"><div><h1>Your progress</h1><p>Every cell is a topic. Red means it needs more work.</p></div><span className="ready-eyebrow"><Target /> Focus dashboard</span></div><section className="ready-card heatmap-card"><div className="section-heading"><h2><Flame /> Skill heatmap</h2><div className="legend"><span><i className="weak" /> Weak</span><span><i className="okay" /> Okay</span><span><i className="strong" /> Strong</span></div></div><div className="heatmap-scroll"><table><thead><tr><th>Subject</th>{TOPICS.DSA.map((_, index) => <th key={index}>Topic {index + 1}</th>)}</tr></thead><tbody>{SUBJECTS.map((subject) => <tr key={subject}><th>{subject}</th>{TOPICS[subject].map((topic) => { const score = scoreFor(subject, topic); return <td key={topic}><button className={scoreTone(score)} onClick={() => setSelected({ subject, topic, score })}>{score}%</button></td>; })}</tr>)}</tbody></table></div></section><section className="ready-card weakest-card"><h2><Target /> Your 3 weakest topics</h2><div className="weakest-grid">{weakest.map((item) => <button key={`${item.subject}-${item.topic}`} onClick={() => setSelected(item)}><small>{item.subject}</small><strong>{item.topic}</strong><span><i style={{ width: `${item.score}%` }} /></span></button>)}</div></section></div>{selected && <aside className="weakness-drawer"><button onClick={() => setSelected(null)}><X /></button><span className={`status ${scoreTone(selected.score)}`}>{scoreTone(selected.score)}</span><small>{selected.subject}</small><h2>{selected.topic}</h2><p>Based on your recent attempts, this topic is a useful place to focus next. A short targeted drill can move your score quickly.</p><button className="ready-primary">Start targeted practice <ArrowRight /></button></aside>}</main>; }

export default function InterviewReady() { const [page, setPage] = useState("home"); return <div className="interview-ready">{page === "home" && <HomePage setPage={setPage} />}{page === "mock" && <MockInterview />}{page === "resume" && <ResumeScanner />}{page === "heatmap" && <Heatmap />}</div>; }
