import React from 'react'
import "./GroupDiscussion.css";
import {FaUsers,FaBrain,FaUserFriends,FaCheckCircle,FaLightbulb,FaCrown,FaComments,FaPlayCircle,} from "react-icons/fa";
import { useNavigate } from 'react-router-dom';

const Groupdisc = () => {
 const navigate = useNavigate();

  const goTogroupPractice = () => {
    navigate("/group-practice");
  };

  return (
  <div className="gd-container">
     
      <div className="gd-header">
        <FaUsers className="gd-icon text-center" />
        <h1>Group Discussion Simulation</h1>
        <p>Practice with AI-powered GD scenarios</p>
      </div>

      <div className="gd-welcome">
        <h2>Welcome to GD Simulation</h2>
        <p>
          Experience realistic group discussions with AI participants. Practice your communication skills,
          learn to present arguments effectively, and receive detailed feedback on your performance.
        </p>

        <div className="gd-cards">
          <div className="gd-card">
            <FaBrain className="card-icon purple" />
            <h3>AI-Generated Topics</h3>
            <p>Choose from various current affairs, business, and social topics generated by AI</p>
          </div>

          <div className="gd-card">
            <FaUserFriends className="card-icon pink" />
            <h3>Realistic Participants</h3>
            <p>Interact with AI participants who have different viewpoints and speaking styles</p>
          </div>
        </div>
         <div className="gd-evaluation">
        <h2>Evaluation Areas</h2>
        <div className="gd-eval-cards">
          <div className="eval-card">
            <FaCheckCircle className="eval-icon green" />
            <p>Participation</p>
          </div>
          <div className="eval-card">
            <FaLightbulb className="eval-icon blue" />
            <p>Relevance</p>
          </div>
          <div className="eval-card">
            <FaCrown className="eval-icon orange" />
            <p>Leadership</p>
          </div>
          <div className="eval-card">
            <FaComments className="eval-icon purple" />
            <p>Communication</p>
          </div>
        </div>
      </div>

       <div className="gd-how">
        <h2>How It Works</h2>
        <div className="steps">
          <div className="step">
            <span className="step-number">1</span>
            <div>
              <h4>Choose Topic</h4>
              <p>Select from current affairs, business, or social topics</p>
            </div>
          </div>
          <div className="step">
            <span className="step-number">2</span>
            <div>
              <h4>Join Discussion</h4>
              <p>Enter the virtual room with 4 AI participants</p>
            </div>
          </div>
          <div className="step">
            <span className="step-number">3</span>
            <div>
              <h4>Participate Actively</h4>
              <p>Share your views, respond to others, and lead discussions</p>
            </div>
          </div>
          <div className="step">
            <span className="step-number">4</span>
            <div>
              <h4>Get Feedback</h4>
              <p>Receive detailed analysis and improvement suggestions</p>
            </div>
          </div>
        </div>
      </div>

      {/* Pro Tips Section */}
      <div className="gd-tips">
        <h2>Pro Tips for Success</h2>
        <ul>
          <li>✔ Listen actively to others' points</li>
          <li>✔ Maintain respectful disagreement</li>
          <li>✔ Stay relevant to the topic</li>
          <li>✔ Support your arguments with examples</li>
          <li>✔ Take initiative to guide discussions</li>
          <li>✔ Conclude with actionable insights</li>
        </ul>
      </div>

       <div className="gd-button" onClick={goTogroupPractice}>
        <button>
          <FaPlayCircle /> Start Group Discussion
        </button>
      </div>

      </div>

     
    </div>
  );
};


export default Groupdisc
