import React, { useState } from 'react'
import "./HRround.css"
import { useNavigate } from 'react-router-dom';

const modes = [
  {
    id: 1,
    title: "Fresher HR Round",
    desc: "Perfect for college students and first-time job seekers. Focus on basics, communication, and potential.",
    level: "Beginner",
    icon: "😊",
  },
  {
    id: 2,
    title: "Internship HR",
    desc: "Tailored for internship applications. Emphasis on learning attitude, skills, and availability.",
    level: "Easy",
    icon: "💼",
  },
  {
    id: 3,
    title: "Experienced Candidate HR",
    desc: "For professionals with work experience. Deep dive into past roles, achievements, and leadership.",
    level: "Intermediate",
    icon: "⏱️",
  },
  {
    id: 4,
    title: "MNC / Startup HR",
    desc: "Company-specific scenarios. Cultural fit, adaptability, and alignment with company values.",
    level: "Advanced",
    icon: "🏢",
  },
  {
    id: 5,
    title: "Stress Interview",
    desc: "High-pressure questions to test composure. Handle difficult situations and challenging queries.",
    level: "Expert",
    icon: "🔥",
  },
];

const steps = [
  {
    step: "01",
    title: "Select Interview Mode",
    desc: "Choose from Fresher, Internship, Experienced, MNC/Startup, or Stress Interview based on your needs.",
    icon: "✔️",
  },
  {
    step: "02",
    title: "Upload Resume & Configure",
    desc: "Upload your resume (optional) and select language preference. AI will analyze your background.",
    icon: "☁️",
  },
  {
    step: "03",
    title: "Face AI HR Interview",
    desc: "Answer dynamic questions generated by AI. Experience real-time reactions and follow-up questions.",
    icon: "💬",
  },
  {
    step: "04",
    title: "Get Detailed Report",
    desc: "Receive comprehensive feedback with scores, strengths, weaknesses, and improvement plan.",
    icon: "📊",
  },
];


const HRround = () => {
  const [selected, setSelected] = useState(null);
const navigate=useNavigate();
  return (
    <div>
    <div className="interview-container-5">
      <h1 className="title-5">Choose Your Interview Mode</h1>
      <p className="subtitle-5">
        Select the interview type that matches your career stage and goals. Our
        AI adapts to your level.
      </p>

      <div className="card-grid-5">
        {modes.map((mode) => (
          <div
            key={mode.id}
            className={`mode-card ${
              selected === mode.id ? "selected" : ""
            }`}
            onClick={() => setSelected(mode.id)}
          >
            <div className="card-header-5">
              <div className="icon-5">{mode.icon}</div>
              <span className="level-5">{mode.level}</span>
            </div>

            <h3>{mode.title}</h3>
            <p>{mode.desc}</p>

            {selected === mode.id && (
              <div className="selected-badge-5">Selected</div>
            )}
          </div>
        ))}
      </div>
 {selected && (
        <button className="continue-btn" onClick={() => navigate('/hr-round-1')}>
          Continue to Setup →
        </button>
      )} 
    </div>
    <section className="how-container">
      <h2 className="how-title">How It Works</h2>
      <p className="how-subtitle">
        Get started in minutes and transform your interview skills with our
        simple 4-step process.
      </p>

      <div className="how-grid">
        {steps.map((item, index) => (
          <div key={index} className="how-card">
            <div className="step-circle">{item.step}</div>

            <div className="icon-box">
              <span>{item.icon}</span>
            </div>

            <h3>{item.title}</h3>
            <p>{item.desc}</p>
          </div>
        ))}
      </div>
    </section>
    </div>
  )
}

export default HRround
